baseurl = "https://example.com/"
publishDir = "docs"
languageCode = "en-US"
title = "Hello"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "alienavatar.jpeg"
  author = "X"
  description = "I really love to dance"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["/css/main.css"]
  custom_js  = []

[params.social]
  Github        = "username"
  Email         = "email@example.com"
  Twitter       = "username"
  LinkedIn      = "username"
  Stackoverflow = "username"

  
[[menu.main]]
  name = "portfolio"
  identifier = "portfolio"
  weight = 2
  url = "/portfolio/"
  
[[menu.main]]
  name = "Om"
  identifier = "om"
  weight = 3
  url = "/om/"
  
  [[menu.main]]
  name = "Kontakt"
  identifier = "kontakt"
  weight = 4
  url = "/kontakt/"