baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hello"
theme = "sustain"


[[menu.main]]
  name = "Forside"
  weight = 1
  identifier = "forside"
  url = "/"
  
[[menu.main]]
  name = "portfolio"
  identifier = "portfolio"
  weight = 2
  url = "/portfolio/"
  
[[menu.main]]
  name = "Om"
  identifier = "om"
  weight = 3
  url = "/om/"
  
  [[menu.main]]
  name = "Kontakt"
  identifier = "kontakt"
  weight = 4
  url = "/kontakt/"