baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hello"
theme = "sustain"


## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
  
[[menu.main]]
  name = "portfolio"
  identifier = "portfolio"
  weight = 200
  url = "/portfolio/"
  
[[menu.main]]
  name = "Kontakt"
  identifier = "kontakt"
  weight = 300
  url = "/kontakt/"